esphome:
  name: roomba
  platform: ESP8266
  board: d1_mini

  includes:
    - roomba_uart_component.h
  libraries:
    #- Roomba=https://github.com/davidecavestro/Roomba.git
    #- Roomba=https://github.com/Apocrathia/Roomba

# Enable logging
logger:
  hardware_uart: UART1
# Enable Home Assistant API
api:

ota:

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200
  debug:
    sequence:
      lambda: UARTDebug::log_int(direction, bytes, ':');


wifi:
  ssid: iBargaggez
  password: "#Ramaiolo1994"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roomba Fallback Hotspot"
    password: asdasdafetgsfds45asd687aw
    
captive_portal:

substitutions:
  init: 'RoombaComponent::instance(id(uart_bus),10000, D2);'

sensor:
  - platform: custom
    lambda: |-
      auto roomba = ${init};
      App.register_component(roomba);
      return {roomba->battery_charge, roomba->battery_temp};
    sensors:
      - name: "Battery"
      - name: "Temperatura roomba"
      
text_sensor:
  - platform: custom
    lambda: |-
      auto roomba = ${init};
      //App.register_component(roomba);
      return {roomba->roombaState};
    text_sensors:
      - name: "State"
        

# custom_component:
# - lambda: |-
#     auto roomba = new RoombaComponent(id(uart_bus),3000,4);
#     App.register_component(roomba);
#     return {roomba};
#   # components:
#   #   - id: roomba
    

